name: Publish
on: 
  push:
    tag: v*
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: get-date
        run: echo "::set-output name=DATE::$(date "+%b %d, %Y")"
      - uses: dante-ev/latex-action@2021-A
        with:
          root_file: "Whoemoon-Jang SWE Resume.tex"
          args: -xelatex -latexoption=-file-line-error -latexoption=-interaction=nonstopmode
          extra_system_packages: |
            texlive-fonts-recommended
            texlive-fonts-extra
            fonts-nanum
      - uses: actions/upload-artifact@v2
        with:
          name: pdfs
          path: "*.pdf"
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Open Resume - Whoemoon Jang (${{ steps.get-date.outputs.DATE }})
          body: |
            This resume is published on ${{ steps.get-date.outputs.DATE }}
          files: Whoemoon-Jang SWE Resume.pdf

